resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml
  - sops-config.yaml

patches:
  - path: argocd-cm.patch.yaml
  - path: argocd-ksops.patch.yaml

namespace: argocd
