apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/services/api/

nameSuffix: -dev

namespace: development

commonLabels:
  environment: dev

patchesStrategicMerge:
  - patch-api-env.yml

