apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    metadata:
      labels:
        app: api
        environment: dev
  selector:
    matchLabels:
      app: api
      environment: dev
