apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

namespace: development

commonLabels:
  environment: dev

patchesStrategicMerge:
  - ./web/patch-web-env.yml
  - ./api/patch-api-env.yml

configMapGenerator:
  - name: ovx-web-config
    literals:
      - PROXY_PATH=http://ovx-api-dev.development.svc.cluster.local:80
