apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../base/services/web/

nameSuffix: -dev

namespace: development

commonLabels:
  environment: dev

patchesStrategicMerge:
  - patch-web-env.yml

generators:
  - secrets-generator.yaml
