apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    metadata:
      labels:
        app: web
        environment: dev
  selector:
    matchLabels:
      app: web
      environment: dev
