apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  project: default
  source:
    path: env/dev/services/api
    repoURL: https://github.com/amarpht336/k8s-demo.git
    targetRevision: HEAD