apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: influeri
  project: default
  source:
    path: env/dev/services/web
    repoURL: https://github.com/amarpht336/k8s-demo.git
    targetRevision: HEAD
